CREATE TABLE IF NOT EXISTS aircraft (
    aircraft_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tail_number VARCHAR(20) NOT NULL,
    model VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS maintenance_event (
    me_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aircraft_id BIGINT NOT NULL,
    description VARCHAR(255) NOT NULL,
    event_date DATE,
    FOREIGN KEY (aircraft_id) REFERENCES aircraft(aircraft_id)
);

CREATE TABLE IF NOT EXISTS seed_status (
    seed_name VARCHAR(50) PRIMARY KEY
);