CREATE TABLE aircraft (
    aircraft_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tail_number VARCHAR(20) NOT NULL,
    model VARCHAR(50) NOT NULL
);

CREATE TABLE maintenance_event (
    me_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aircraft_id BIGINT NOT NULL,
    description VARCHAR(255) NOT NULL,
    event_date DATE,
    FOREIGN KEY (aircraft_id) REFERENCES aircraft(aircraft_id)
);